server.port: 7003
server.error.include-message: always
server.forward-headers-strategy: framework

spring.data.mongodb:
  host: localhost
  port: 27017
  database: onesty-db-search
  auto-index-creation: true

logging:
  level:
    root: INFO
    com.onesty: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8082

spring.data.mongodb.host: mongodb