server.port: 7002
server.error.include-message: always
server.forward-headers-strategy: framework

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: images
---
spring.config.activate.on-profile: docker

server.port: 8081